module.exports = [
  {
    "service_type": "Website Sekolah",
    "name": "Paket Standard",
    "price": "Rp. 4.000.000",
    "target": "Cocok untuk SD, SMP, SMA, dan SMK yang membutuhkan website profil institusi.",
    "duration": "Estimasi pengerjaan: 15 - 30 hari kerja",
    "features": [
      "Panel Admin (CMS)",
      "Login Admin",
      "Profil Sekolah & Sejarah",
      "Visi & Misi",
      "Informasi Guru & Staff",
      "Informasi Program & Ekstrakurikuler",
      "Berita, Artikel & Pengumuman",
      "Galeri Foto/Video",
      "Formulir Kontak",
      "Page Builder",
      "Integrasi WhatsApp",
      "Integrasi Google Maps",
      "Responsive (Mobile & Desktop)",
      "Desain Website Profesional & Modern",
      "SEO Dasar"
    ],
    "is_popular": 0,
    "sort_order": 100,
    "status": "Active"
  },
  {
    "service_type": "Website Sekolah",
    "name": "Paket Profesional",
    "price": "Rp. 8.000.000",
    "target": "Cocok untuk sekolah yang membutuhkan sistem informasi dan layanan akademik yang lebih lengkap.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Semua fitur Standard, ditambah:",
      "Sistem PPDB (Penerimaan Peserta Didik Baru)",
      "Portal Siswa",
      "Portal Guru",
      "Download Dokumen & Formulir",
      "Dashboard Statistik Pengunjung",
      "Dashboard Laporan & Statistik",
      "Integrasi Pembayaran SPP",
      "Multi User Admin",
      "Role & Permission Management",
      "Backup Database Berkala"
    ],
    "is_popular": 1,
    "sort_order": 101,
    "status": "Active"
  },
  {
    "service_type": "Website Sekolah",
    "name": "Paket Premium",
    "price": "Rp. 15.000.000+",
    "target": "Cocok untuk sekolah yang membutuhkan sistem akademik terintegrasi.",
    "duration": "Estimasi pengerjaan: 60 - 90 hari kerja",
    "features": [
      "Semua fitur Profesional, ditambah:",
      "E-Learning",
      "Absensi Online",
      "E-Rapor",
      "Jadwal Pelajaran Online",
      "Portal Orang Tua/Wali Murid",
      "Integrasi Pembayaran SPP",
      "Notifikasi Email & WhatsApp",
      "Dashboard Akademik",
      "Sistem Akademik Sesuai Kebutuhan",
      "SSL Premium & Security Hardening",
      "Fitur Kustom Sesuai Kebutuhan Sekolah"
    ],
    "is_popular": 0,
    "sort_order": 102,
    "status": "Active"
  },
  {
    "service_type": "Website Kampus/Universitas",
    "name": "Paket Standard",
    "price": "Rp. 7.500.000",
    "target": "Cocok untuk kampus, sekolah tinggi, atau akademi yang membutuhkan website profil institusi.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Panel Admin (CMS)",
      "Profil Kampus & Sejarah",
      "Visi & Misi",
      "Informasi Program Studi",
      "Informasi Fakultas & Dosen",
      "Manajemen Berita, Artikel & Pengumuman",
      "Page Builder",
      "Galeri Foto/Video",
      "Formulir Kontak",
      "Integrasi WhatsApp",
      "Integrasi Google Maps",
      "Responsive (Mobile & Desktop)",
      "Desain Website Profesional & Modern",
      "SEO Dasar"
    ],
    "is_popular": 0,
    "sort_order": 200,
    "status": "Active"
  },
  {
    "service_type": "Website Kampus/Universitas",
    "name": "Paket Profesional",
    "price": "Rp. 12.000.000+",
    "target": "Cocok untuk kampus yang membutuhkan sistem informasi dan pengelolaan konten yang lebih lengkap.",
    "duration": "Estimasi pengerjaan: 60 - 90 hari kerja",
    "features": [
      "Semua fitur Standard, ditambah:",
      "Sistem PMB (Penerimaan Mahasiswa Baru) Online",
      "Portal Mahasiswa",
      "Integrasi Pembayaran UKT/SPP",
      "Portal Dosen",
      "Sistem Akademik Sesuai Kebutuhan",
      "Jadwal Perkuliahan",
      "Download Dokumen & Formulir",
      "Halaman Karir & Alumni",
      "Role & Permission Management",
      "Multi User Admin",
      "Dashboard Laporan & Statistik",
      "Dashboard Statistik Pengunjung",
      "Backup Database Berkala",
      "Fitur Kustom Sesuai Kebutuhan Kampus"
    ],
    "is_popular": 1,
    "sort_order": 201,
    "status": "Active"
  },
  {
    "service_type": "Website Kursus & Bimbingan Belajar",
    "name": "Paket Standard",
    "price": "Rp. 6.000.000",
    "target": "Cocok untuk lembaga kursus yang membutuhkan website profil dan informasi program belajar.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Panel Admin (CMS)",
      "Login Admin",
      "Profil Lembaga Kursus",
      "Informasi Program & Kelas",
      "Profil Pengajar",
      "Jadwal Kelas",
      "Pendaftaran Siswa Online",
      "Manajemen Berita & Pengumuman",
      "Page Builder",
      "Integrasi WhatsApp",
      "Integrasi Google Maps",
      "Responsive (Mobile & Desktop)",
      "Desain Profesional & Modern",
      "SEO Dasar"
    ],
    "is_popular": 0,
    "sort_order": 300,
    "status": "Active"
  },
  {
    "service_type": "Website Kursus & Bimbingan Belajar",
    "name": "Paket Profesional",
    "price": "Rp. 12.000.000+",
    "target": "Cocok untuk lembaga kursus yang membutuhkan sistem pendaftaran dan pengelolaan siswa.",
    "duration": "Estimasi pengerjaan: 60 - 90 hari kerja",
    "features": [
      "Semua fitur Standard, ditambah:",
      "Portal Siswa",
      "Portal Pengajar",
      "E-Learning",
      "Video Pembelajaran Online",
      "Kuis & Ujian Online",
      "Sertifikat Digital Otomatis",
      "Absensi Online",
      "Dashboard Laporan & Statistik",
      "Integrasi Pembayaran",
      "Multi Users",
      "Role & Permission Management",
      "Backup Database Berkala",
      "Fitur Kustom Sesuai Kebutuhan Lembaga"
    ],
    "is_popular": 1,
    "sort_order": 301,
    "status": "Active"
  },
  {
    "service_type": "Website LPK",
    "name": "Paket Standard",
    "price": "Rp. 6.000.000",
    "target": "Cocok untuk LPK yang membutuhkan sistem profil dan pendaftaran peserta yang lebih lengkap.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Panel Admin (CMS)",
      "Login Admin",
      "Profil LPK & Tentang Kami",
      "Visi & Misi",
      "Informasi Program Pelatihan",
      "Profil Instruktur/Pengajar",
      "Jadwal Pelatihan",
      "Informasi Penempatan Kerja",
      "Berita & Pengumuman",
      "Galeri Foto/Video",
      "Formulir Pendaftaran Online",
      "Page Builder",
      "Integrasi WhatsApp",
      "Integrasi Google Maps",
      "Responsive (Mobile & Desktop)",
      "Desain Website Profesional & Modern",
      "SEO Dasar"
    ],
    "is_popular": 0,
    "sort_order": 400,
    "status": "Active"
  },
  {
    "service_type": "Website LPK",
    "name": "Paket Profesional",
    "price": "Rp. 10.000.000+",
    "target": "Cocok untuk lembaga khusus yang membutuhkan sistem pendaftaran dan pengelolaan siswa.",
    "duration": "Estimasi pengerjaan: 60 - 90 hari kerja",
    "features": [
      "Semua fitur Standard, ditambah:",
      "Portal Peserta",
      "Portal Instruktur",
      "Dashboard Peserta",
      "Login Peserta & Instruktur",
      "Manajemen Materi Pelatihan",
      "Upload Modul & Dokumen",
      "Sertifikat Digital Otomatis",
      "Dashboard Laporan & Statistik",
      "Multi User Admin",
      "Role & Permission Management",
      "Backup Database Berkala",
      "Integrasi Pembayaran",
      "Fitur Kustom Sesuai Kebutuhan LPK"
    ],
    "is_popular": 1,
    "sort_order": 401,
    "status": "Active"
  },
  {
    "service_type": "Website Desa",
    "name": "Paket Standard",
    "price": "Rp. 4.000.000",
    "target": "Cocok untuk desa yang membutuhkan website profil dan media informasi desa.",
    "duration": "Estimasi pengerjaan: 15 - 30 hari kerja",
    "features": [
      "Panel Admin (CMS)",
      "Login Admin",
      "Profil Desa & Sejarah",
      "Visi & Misi Desa",
      "Profil Aparatur Desa",
      "Informasi Potensi Desa",
      "Berita & Pengumuman Desa",
      "Galeri Foto/Video",
      "Formulir Kontak",
      "Page Builder",
      "Integrasi WhatsApp",
      "Integrasi Google Maps",
      "Responsive (Mobile & Desktop)",
      "Desain Website Profesional & Modern",
      "SEO Dasar"
    ],
    "is_popular": 0,
    "sort_order": 500,
    "status": "Active"
  },
  {
    "service_type": "Website Desa",
    "name": "Paket Profesional",
    "price": "Rp. 8.000.000",
    "target": "Cocok untuk desa yang membutuhkan layanan administrasi dan informasi yang lebih lengkap.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Semua fitur Standard, ditambah:",
      "Sistem Pengajuan Surat Online",
      "Download Formulir & Dokumen Desa",
      "Layanan Administrasi Desa",
      "Dashboard Statistik Pengunjung",
      "Dashboard Data Penduduk Dasar",
      "Multi User Admin",
      "Role & Permission Management",
      "Manajemen Berita, Pengumuman, Artikel",
      "Manajemen Laporan",
      "Backup Database Berkala"
    ],
    "is_popular": 1,
    "sort_order": 501,
    "status": "Active"
  },
  {
    "service_type": "Website Desa",
    "name": "Paket Premium",
    "price": "Rp. 15.000.000+",
    "target": "Cocok untuk desa yang membutuhkan sistem pelayanan masyarakat dan administrasi desa terintegrasi.",
    "duration": "Estimasi pengerjaan: 60 - 120 hari kerja",
    "features": [
      "Semua fitur Profesional, ditambah:",
      "Portal Warga",
      "Sistem Layanan Publik Online",
      "Tracking Status Pengajuan Surat",
      "Pengelolaan Data Penduduk",
      "Pengelolaan Data Kartu Keluarga (KK)",
      "Pengelolaan Data Wilayah Dusun, RT & RW",
      "Pengelolaan Dokumen Desa",
      "Dashboard Statistik Kependudukan",
      "Sistem Pengaduan Masyarakat",
      "Notifikasi Email & WhatsApp",
      "Dashboard Laporan & Statistik",
      "SSL Premium & Security Hardening",
      "Fitur Kustom Sesuai Kebutuhan Desa"
    ],
    "is_popular": 0,
    "sort_order": 502,
    "status": "Active"
  },
  {
    "service_type": "Website Profil Perusahaan",
    "name": "Paket Standard",
    "price": "Rp. 3.500.000",
    "target": "Cocok untuk UMKM, startup, dan perusahaan yang membutuhkan website company profile sederhana.",
    "duration": "Estimasi pengerjaan: 15 - 30 hari kerja",
    "features": [
      "Profil Perusahaan & Tentang Kami",
      "Visi & Misi",
      "Produk & Layanan",
      "Galeri Foto/Video",
      "Formulir Kontak",
      "Integrasi WhatsApp",
      "Integrasi Google Maps",
      "Responsive (Mobile & Desktop)",
      "Desain Profesional & Modern",
      "SEO Dasar"
    ],
    "is_popular": 0,
    "sort_order": 600,
    "status": "Active"
  },
  {
    "service_type": "Website Profil Perusahaan",
    "name": "Paket Profesional",
    "price": "Rp. 7.000.000+",
    "target": "Cocok untuk bisnis yang membutuhkan layanan digital dan integrasi sistem internal.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Semua fitur standard, ditambah:",
      "Panel Admin (CMS)",
      "Manajemen Berita, Artikel, Pengumuman",
      "Manajemen Produk & Layanan",
      "Page Builder",
      "Halaman Karir & Rekrutmen",
      "Download Dokumen/Katalog",
      "Multi User Admin",
      "Data Staf/Pegawai",
      "AI Live Chat",
      "Dashboard Statistik Pengunjung",
      "Backup Database Berkala",
      "Fitur Kustom Sesuai Kebutuhan"
    ],
    "is_popular": 1,
    "sort_order": 601,
    "status": "Active"
  },
  {
    "service_type": "Website Kantor Hukum",
    "name": "Paket Standard",
    "price": "Rp. 3.500.000",
    "target": "Cocok untuk kantor hukum yang membutuhkan website company profile profesional.",
    "duration": "Estimasi pengerjaan: 15 - 30 hari kerja",
    "features": [
      "Profil Kantor Hukum",
      "Profil Advokat & Tim",
      "Layanan Bantuan Hukum",
      "Konsultasi Online",
      "Artikel & Informasi Hukum",
      "Galeri Foto/Video",
      "Formulir Konsultasi",
      "Integrasi WhatsApp",
      "Integrasi Google Maps",
      "Responsive (Mobile & Desktop)",
      "Desain Profesional & Modern",
      "SEO Dasar"
    ],
    "is_popular": 0,
    "sort_order": 700,
    "status": "Active"
  },
  {
    "service_type": "Website Kantor Hukum",
    "name": "Paket Profesional",
    "price": "Rp. 5.000.000",
    "target": "Cocok untuk kantor hukum yang membutuhkan pengelolaan konten dan layanan konsultasi online.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Semua fitur Standard, ditambah:",
      "Panel Admin (CMS)",
      "Login Admin",
      "Dashboard Laporan & Statistik",
      "Manajemen Profil Advokat",
      "Manajemen Berita",
      "Page Builder",
      "Form Booking Konsultasi Online",
      "Tracking Status Penanganan Perkara",
      "Data Advokat",
      "Download Dokumen & Legal Template"
    ],
    "is_popular": 1,
    "sort_order": 701,
    "status": "Active"
  },
  {
    "service_type": "Website Kantor Hukum",
    "name": "Paket Premium",
    "price": "Rp. 8.000.000+",
    "target": "Cocok untuk firma hukum yang membutuhkan sistem layanan digital dan fitur khusus.",
    "duration": "Estimasi pengerjaan: 60 - 90 hari kerja",
    "features": [
      "Semua fitur Profesional, ditambah:",
      "Portal Klien",
      "Role & Permission Management Users",
      "Sistem Pengajuan Konsultasi Online",
      "Upload Dokumen Klien",
      "Dashboard Laporan & Statistik",
      "Manajemen Berita, Pengumuman & Artikel",
      "Halaman Karir & Rekrutmen",
      "Data Staf & Advokat",
      "AI Live Chat",
      "Backup Database Berkala",
      "SSL Premium & Security Hardening",
      "Fitur Kustom Sesuai Kebutuhan Kantor Hukum"
    ],
    "is_popular": 0,
    "sort_order": 702,
    "status": "Active"
  },
  {
    "service_type": "Website Bank",
    "name": "Paket Standard",
    "price": "Rp. 10.000.000",
    "target": "Cocok untuk BPR, BPRS, koperasi simpan pinjam, atau bank yang hanya membutuhkan company profile digital.",
    "duration": "Estimasi pengerjaan: 30 - 60 hari kerja",
    "features": [
      "Panel Admin (CMS)",
      "Profil perusahaan & sejarah bank",
      "Informasi produk tabungan & kredit",
      "Informasi layanan dan kantor cabang",
      "Manajemen Berita & Pengumuman & Banner",
      "Galeri foto/video",
      "Page Builder",
      "Formulir kontak",
      "Integrasi Google Maps",
      "Integrasi WhatsApp",
      "Responsive (Mobile & Desktop)",
      "Desain profesional dan modern",
      "SEO dasar"
    ],
    "is_popular": 0,
    "sort_order": 800,
    "status": "Active"
  },
  {
    "service_type": "Website Bank",
    "name": "Paket Profesional",
    "price": "Rp. 18.000.000+",
    "target": "Cocok untuk bank yang membutuhkan layanan digital dan integrasi sistem internal.",
    "duration": "Estimasi pengerjaan: 30 - 90 hari kerja",
    "features": [
      "Semua fitur Standard, ditambah:",
      "Form Pengajuan Pembiayaan/Kredit Online",
      "Form Pembukaan Rekening Online",
      "Download Formulir & Dokumen",
      "Fitur Produk & Layanan (tabungan, deposito, pembiayaan, Simulasi Angsuran/Kalkulator Pembiayaan)",
      "Halaman Karir & Rekrutmen",
      "AI Live Chat",
      "Sistem Login & Registrasi Pengguna",
      "Login Manual atau Akun Google (Google OAuth)",
      "Dashboard Pengguna/Nasabah",
      "Dashboard Statistik & Laporan",
      "Audit Log Aktivitas",
      "Backup Database Berkala",
      "Fitur kustom Sesuai Kebutuhan Bank"
    ],
    "is_popular": 1,
    "sort_order": 801,
    "status": "Active"
  },
  {
    "service_type": "Undangan Digital",
    "name": "Paket Standard",
    "price": "Rp. 200.000",
    "target": "Cocok untuk pasangan yang menginginkan undangan digital dengan desain siap pakai (template).",
    "duration": "Estimasi pengerjaan: 1 - 2 hari kerja",
    "features": [
      "Semua fitur admin panel tersedia",
      "Dashboard pengelolaan undangan",
      "Kelola data mempelai & acara",
      "Kelola foto & musik",
      "Buat link undangan tamu otomatis",
      "RSVP / Konfirmasi kehadiran",
      "Buku tamu & ucapan",
      "Statistik pengunjung (Page Views)",
      "Share ke WhatsApp & Media Sosial",
      "Menggunakan template yang sudah tersedia"
    ],
    "is_popular": 0,
    "sort_order": 900,
    "status": "Active"
  },
  {
    "service_type": "Undangan Digital",
    "name": "Paket Profesional",
    "price": "Rp. 350.000",
    "target": "Cocok untuk pasangan yang menginginkan tampilan undangan yang lebih eksklusif.",
    "duration": "Estimasi pengerjaan: 3 - 10 hari kerja",
    "features": [
      "Semua fitur standard, ditambah:",
      "Semua fitur Paket Basic",
      "Desain template custom sesuai permintaan",
      "Custom warna, font, dan layout",
      "Penyesuaian animasi dan elemen visual",
      "Tampilan undangan eksklusif dan unik",
      "Revisi desain maksimal 5 kali",
      "Prioritas pengerjaan"
    ],
    "is_popular": 1,
    "sort_order": 901,
    "status": "Active"
  }
];
